"""Source-only route surfaces explicitly owned by the sampled physical endpoint.

These compilation annotations do not add extraction-label fields. Their values
come from the pinned route scenario, including its latent country/UNLOCODE, and
are never independently generated by the prose editor.
"""

from __future__ import annotations

import re
from collections.abc import Mapping, Sequence
from copy import deepcopy
from typing import Any

DERIVATIONS = frozenset(
    {
        "sampled_route_name",
        "sampled_route_country",
        "sampled_route_country_code",
        "sampled_route_subdivision_code",
        "sampled_route_location",
        "sampled_route_locode",
        "sampled_route_terminal",
    }
)
_TERMINAL = re.compile(
    r"(?P<name>[A-Za-z][A-Za-z0-9 .&/'-]*?)\s+"
    r"(?P<kind>CONTAINER\s+)?(?P<noun>TERMINAL|TERM|TER)"
    r"(?P<number>\s+[0-9]+)?\.?",
    re.I,
)


def _terminal_suffix(binding: Any) -> str:
    """A synthetic terminal belongs to its port, not a real terminal registry.

    Keep the printed terminal class/number while replacing the complete proper
    name. This cannot interpret an inland city, country or an arbitrary sentence
    as a terminal. Role ownership requires compilation evidence review.
    """
    suffixes = set()
    for slot in binding.occurrences:
        match = _TERMINAL.fullmatch(slot.source_text.strip())
        if match is None:
            raise ValueError("route terminal lacks a complete typed terminal-name surface")
        suffixes.add(
            (" Container" if match["kind"] else "")
            + " "
            + match["noun"].title()
            + (match["number"] or "")
        )
    if len(suffixes) != 1:
        raise ValueError("route terminal occurrences have incompatible terminal kinds")
    return suffixes.pop()


_OWNER = re.compile(
    r"documentPatch\.route\.(portOfLoading|portOfDischarge|transshipmentPort|placeOfReceipt|placeOfDelivery)"
    r"(?:\.(?:name|country))?"
)


def supports_transshipment(bindings: Sequence[Any]) -> bool:
    """Report compiled support from the owning target or dependency paths."""

    return any(
        path == "documentPatch.route.transshipmentPort"
        or path.startswith("documentPatch.route.transshipmentPort.")
        for binding in bindings
        for path in (*binding.target_paths, *binding.dependency_paths)
    )


def endpoint(binding: Any) -> str:
    if binding.derivation not in DERIVATIONS:
        raise ValueError("binding is not a sampled-route derivation")
    if (
        binding.target_paths
        or binding.dependency_bindings
        or len(binding.dependency_paths) != 1
        or binding.group_kind != "route"
        or binding.value_kind != "location"
        or binding.render_mode != "deterministic_derived"
    ):
        raise ValueError("sampled-route surface requires one route owner and no target leaves")
    match = _OWNER.fullmatch(binding.dependency_paths[0])
    if match is None:
        raise ValueError("sampled-route dependency is not a supported physical endpoint")
    if binding.derivation in {"sampled_route_terminal", "sampled_route_subdivision_code"} and match[
        1
    ] not in {
        "portOfLoading",
        "portOfDischarge",
        "transshipmentPort",
    }:
        raise ValueError(
            "route terminal/subdivision requires an explicit "
            "loading/discharge/transshipment port owner"
        )
    return match[1]


def values(bindings: Sequence[Any], scenario: Mapping[str, Any]) -> dict[str, str]:
    result = {}
    for binding in bindings:
        if binding.derivation not in DERIVATIONS:
            continue
        role = endpoint(binding)
        location = (
            scenario["loadingPort"]
            if role == "portOfLoading"
            else scenario["dischargePort"]
            if role == "portOfDischarge"
            else scenario["routeLocations"][role]
        )
        field = binding.derivation.removeprefix("sampled_route_")
        if field == "terminal":
            # Explicitly synthetic operational wording; never an assertion that
            # the selected registry port has a real facility by this name.
            result[binding.logical_key] = location["name"] + _terminal_suffix(binding)
            continue
        value = (
            f"{location['name']}, {location['countryName']}"
            if field == "location"
            else location[
                {
                    "name": "name",
                    "country": "countryName",
                    "country_code": "countryCode",
                    "subdivision_code": "subdivisionCode",
                    "locode": "locode",
                }[field]
            ]
        )
        if not isinstance(value, str) or not value.strip():
            raise ValueError("sampled route lacks the explicitly required auxiliary fact")
        result[binding.logical_key] = value
    return result


def physical_source(target: Mapping[str, Any], bindings: Sequence[Any]) -> dict[str, Any]:
    """Expose explicitly owned, unlabelled endpoints only to the physical sampler.

    A printed port or place of receipt need not be an extraction-label field. Its source
    name/country spans are sufficient to create a private route observation;
    they are not permission to infer a city from a street or merge two roles.
    """
    result = deepcopy(dict(target))
    route = result["documentPatch"].setdefault("route", {})
    observations: dict[str, dict[str, str]] = {}
    for binding in bindings:
        if binding.derivation not in DERIVATIONS:
            continue
        role = endpoint(binding)
        existing = target["documentPatch"].get("route", {}).get(role)
        if binding.derivation not in {
            "sampled_route_name",
            "sampled_route_country",
            "sampled_route_country_code",
        }:
            if existing is not None:
                continue
            raise ValueError("latent endpoint requires separate name/country source evidence")
        field = binding.derivation.removeprefix("sampled_route_")
        surfaces = {" ".join(s.source_text.casefold().split()) for s in binding.occurrences}
        if len(surfaces) != 1:
            raise ValueError("latent endpoint has non-equivalent source observations")
        value = binding.occurrences[0].source_text
        observed = observations.setdefault(role, {})
        if field in observed and observed[field].casefold() != value.casefold():
            raise ValueError("latent endpoint source facts disagree")
        observed[field] = value
    for role, observation in observations.items():
        current = route.setdefault(role, {})
        if "name" not in observation and "name" not in current:
            raise ValueError("latent endpoint lacks a printed name")
        for field in ("name", "country"):
            if field not in current and field in observation:
                current[field] = observation[field]
        if "country" not in current and "country_code" in observation:
            current["country"] = observation["country_code"]
    return result


def validate_source(target: Mapping[str, Any], bindings: Sequence[Any]) -> None:
    """Prove source surface types independently of an agent's ownership rationale.

    A state code is not a combined port/country surface. Role ownership still
    requires semantic review, but an approving critic cannot waive this invariant.
    """
    from .host import _surface_match

    physical = physical_source(target, bindings)
    for binding in bindings:
        if binding.derivation not in DERIVATIONS:
            continue
        owner = physical["documentPatch"]["route"][endpoint(binding)]
        field = binding.derivation.removeprefix("sampled_route_")
        if field == "terminal":
            _terminal_suffix(binding)
            if not owner.get("name"):
                raise ValueError("route terminal requires a separately printed port name")
            continue
        for slot in binding.occurrences:
            text = slot.source_text.strip()
            if field == "country_code":
                valid = re.fullmatch(r"[A-Za-z]{2}", text) is not None
            elif field == "subdivision_code":
                # The pinned port registry proves the semantic code in
                # validate_subdivision_evidence before any candidate is drawn.
                valid = re.fullmatch(r"[A-Z0-9]{1,3}", text, re.I) is not None
            elif field == "locode":
                valid = re.fullmatch(r"[A-Za-z]{2}[A-Za-z0-9]{3}", text) is not None
            else:
                expected = (
                    owner.get("name")
                    if field == "name"
                    else owner.get("country")
                    if field == "country"
                    else f"{owner['name']}, {owner['country']}"
                    if owner.get("name") and owner.get("country")
                    else None
                )
                if expected is None:
                    raise ValueError("source endpoint lacks evidence for its declared surface type")
                valid = _surface_match(
                    source=text, target=expected, adapter="natural_text", value_kind="location"
                ) == ("", "")
                if not valid and field == "location":
                    # A complete name IN country is the same typed location as
                    # name, country. Do not discard arbitrary intermediate words
                    # or accept a state code as either of those two fields.
                    parts = re.split(r"\s+IN\s+", text, flags=re.I)
                    valid = len(parts) == 2 and all(
                        _surface_match(
                            source=part,
                            target=owner[key],
                            adapter="natural_text",
                            value_kind="location",
                        )
                        == ("", "")
                        for part, key in zip(parts, ("name", "country"), strict=True)
                    )
            if not valid:
                raise ValueError(
                    "source route surface does not prove its declared "
                    + field
                    + " type: "
                    + binding.logical_key
                )


def validate_subdivision_evidence(
    target: Mapping[str, Any], bindings: Sequence[Any], *, support: Any, countries: Any
) -> None:
    """Resolve the exact source port and state code against the pinned registry.

    A state abbreviation is neither a country nor an independently sampled
    locality. Only a unique matching maritime port proves this contract; no
    city-from-address inference or geographical default is involved.
    """
    from document_ocr.synthesis.shipment_scenarios import normalize_location_name

    for binding in bindings:
        if binding.derivation != "sampled_route_subdivision_code":
            continue
        owner = target["documentPatch"]["route"][endpoint(binding)]
        country = countries.resolve(owner["country"]) if "country" in owner else None
        if "country" in owner and country is None:
            raise ValueError("source port subdivision has an unresolved country")
        codes = {s.source_text.strip().upper() for s in binding.occurrences}
        if len(codes) != 1:
            raise ValueError("one source port has conflicting subdivision codes")
        code = codes.pop()
        name = normalize_location_name(owner["name"])
        candidates = {
            port.locode
            for key, ports in support.maritime_by_country.items()
            if country is None or key == country
            for port in ports
            if port.subdivision_code == code
            and name
            in {
                normalize_location_name(port.name),
                normalize_location_name(port.name + " " + code),
            }
        }
        if len(candidates) != 1:
            raise ValueError("source port subdivision lacks a unique pinned registry identity")
